# Base image SQL Server
FROM mcr.microsoft.com/mssql/server:2022-latest

ENV ACCEPT_EULA=Y

ENV SA_PASSWORD=3Ban@12345

EXPOSE 1433


# docker run -d -p 1433:1433 -v sqlserver_data:/var/opt/mssql --name my-sqlserver-container --restart always sql-server
